"""hapus fields prefer_caring_partner

Revision ID: 0aabc6775aa7
Revises: 5ef662256f2a
Create Date: 2025-06-17 19:40:28.792074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aabc6775aa7'
down_revision = '5ef662256f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences_similarity', schema=None) as batch_op:
        batch_op.drop_column('prefer_caring_partner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences_similarity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefer_caring_partner', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
