"""hapus 2 fields

Revision ID: 3369920207a9
Revises: 77289293a19c
Create Date: 2025-06-17 20:23:56.046199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3369920207a9'
down_revision = '77289293a19c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_image_tests', schema=None) as batch_op:
        batch_op.drop_column('image_choice')
        batch_op.drop_column('meaning')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_image_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meaning', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_choice', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
