"""update db

Revision ID: 40508f120dbb
Revises: acc80b103d9a
Create Date: 2025-06-17 03:26:00.437237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40508f120dbb'
down_revision = 'acc80b103d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smoking', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('alcohol', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('relationship_goal', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('relationship_goal')
        batch_op.drop_column('alcohol')
        batch_op.drop_column('smoking')

    # ### end Alembic commands ###
