"""Move outdoor_activity from UserProfile to UserPreferencesSimilarity

Revision ID: 530dbc273976
Revises: 40508f120dbb
Create Date: 2025-06-17 12:41:14.861924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530dbc273976'
down_revision = '40508f120dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences_similarity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outdoor_activity', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('outdoor_activity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outdoor_activity', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('user_preferences_similarity', schema=None) as batch_op:
        batch_op.drop_column('outdoor_activity')

    # ### end Alembic commands ###
