"""hapus fields okay_with_pets

Revision ID: 5ef662256f2a
Revises: 530dbc273976
Create Date: 2025-06-17 15:57:34.458234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef662256f2a'
down_revision = '530dbc273976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences_similarity', schema=None) as batch_op:
        batch_op.drop_column('okay_with_pets')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences_similarity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('okay_with_pets', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
