"""add_preferred_cluster_ids_to_user_image_tests

Revision ID: 77289293a19c
Revises: 0aabc6775aa7
Create Date: 2025-06-17 20:20:48.201509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77289293a19c'
down_revision = '0aabc6775aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_image_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_cluster_ids', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_image_tests', schema=None) as batch_op:
        batch_op.drop_column('preferred_cluster_ids')

    # ### end Alembic commands ###
