"""update db

Revision ID: acc80b103d9a
Revises: 5b04fcb8eef6
Create Date: 2025-06-17 03:11:47.513232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc80b103d9a'
down_revision = '5b04fcb8eef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outdoor_activity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('outdoor_activity')

    # ### end Alembic commands ###
